version: "3.3"
services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - COM=www.devops.lviv.ua google.com:80,voip.kramarets.net yandex.ru:80
      - EMAIL="taras@kramarets.net"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
